Noexcept specifier:

- The noexcept specifier specifies whether a function could throw
  exceptions. It is an improved version ot throw().
  
  void func1() noexcept; // does not allow
  void func2() noexcept(true); // does not throw
  void func2() throw(); // does not throw
  
  void func4() noexcept(false); // may throw
  
- Non-throwing functions are permitted to call potentially throwing
  functions. 

- Whenever an exception is thrown and the search for a handler
  encounters the outermost block of a non-throwing function, 
  the function std::terminate is called.
  
  extern void f(); //potentially-throwing
  void g() noexcept {
    f();      // valid,even if f throws 
	throw 42; // valid, effectively a call to std::terminate
  }